### ISSUE TITLE
Fix HotOrNot SNS name on ICP Coins

### ISSUE THREAD

**Issue by ishaaqziyan** [Neutrinomic/icpcoins#5]
As HotOrNot Rebrands to Yral-app please consider fixing this on the ICPcoins Frontend
References: `https://twitter.com/Yral_app`
Thanks

**Comment by infu** [comment]
We should use the official name from SNS. Perhaps change it here first https://dashboard.internetcomputer.org/sns/67bll-riaaa-aaaaq-aaauq-cai

**Comment by ishaaqziyan** [comment]
Noted ser
Thank you for the clarification🫡

**Comment by ishaaqziyan** [comment]
Noted ser
Thank you for the clarification🫡
